name: Build and Push 
run-name: ${{ github.actor }} is testing out Building the project
on: [push]
jobs:
  # Build-Lead360:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  #     - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
  #     - run: echo "🖥️ The workflow is now ready to test your code on the runner."
  #     - name: List files in the repository
  #       run: |
  #         ls ${{ github.workspace }}
  #     - run: echo "🍏 This job's status is ${{ job.status }}."
  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v4.0.3
  #       with:
  #         # Set always-auth in npmrc.
  #         always-auth: false
  #         # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
  #         # node-version: 18.17.1
  #         # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
  #         node-version-file: package.json
  #     - name: Setup NVM and yarn
  #       run: |
  #         sudo apt-get install curl
  #         curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
  #         corepack enable
  #     - name: Setup PostgreSQL Database
  #       run: make postgres-on-linux
  #     - name: Setup Environment variables
  #       run: | 
  #         cp ./packages/twenty-front/.env.example ./packages/twenty-front/.env
  #         cp ./packages/twenty-server/.env.example ./packages/twenty-server/.env
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Build Project
  #       run: |
  #         npx nx database:reset twenty-server
  #         npx nx build twenty-server
  #         npx nx build twenty-front
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      # - name: Install Docker
        # You may pin to the exact commit or the version.
        # uses: papodaca/install-docker-action@6689d765bf69e0b79e9352e11203caf4acd1d25c
      #   uses: papodaca/install-docker-action@v1
      - name: Build Lead360 Database
        uses: docker/build-push-action@v6.4.0
        with:
          file: ./DockerfileDB
          tags: db360:latest
      # - name: Build Lead360
      #   # You may pin to the exact commit or the version.
      #   # uses: docker/build-push-action@a254f8ca60a858f3136a2f1f23a60969f2c402dd
      #   uses: docker/build-push-action@v6.4.0
      #   with:
      #     file: ./Dockerfile
          # tags: latest
      - name: GitHub Action for DigitalOcean - doctl
        # You may pin to the exact commit or the version.
        # uses: digitalocean/action-doctl@135ac0aa0eed4437d547c6f12c364d3006b42824
        uses: digitalocean/action-doctl@v2.5.1
        with:
          # Skip authentication
          no_auth: TRUE
          # DigitalOcean API Token
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - name: push-db360
        run: |
              doctl auth init ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
              docker tag db360:latest  registry.digitalocean.com/twentydocker/d360
              docker push registry.digitalocean.com/twentydocker/d360

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Log in to Digital Ocean Container Registry
      #   run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_USERNAME }} --password-stdin
      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v6.4.0
      #   with:
      #     context: .
      #     file: ./DockerfileDB
      #     # platforms: linux/amd64
      #     tags: registry.digitalocean.com/twentydocker/ld360:latest
      #     push: true
            
      
          
      
            
